# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEmployee', 
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patronymic_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[               
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='library_card_number')),
                ('name', models.CharField(max_length=30)),
                ('patronymic_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30),
                ('passport_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('grop_number', models.IntegerField())
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[      
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_copy', models.ForeignKey('BookCopy'))
                ('library_card_number', models.ForeignKey('Reader')),
                ('library_employee', models.ForeignKey('LibraryEmployee')),
                ('operation_date', models.DateField()),
                ('required_return_date', models.DateField(),
            ],
        ),
    ]
